### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` / `removeListeners` method.

### ISSUE THREAD

**Issue by junaedsiam** [getsocial-im/getsocial-react-native-sdk#56]
On react native version 0.69.6, this warning pops up. Here is the full warning log for required **addListener**

```
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
at node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:62:8 in constructor
at node_modules/getsocial-react-native-sdk/GetSocialEventEmitter.js:9:9 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/utils/JSONBridge.js:63:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/GetSocial.js:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/services/auth/hooks/useAuth.ts:31:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/services/auth/hooks/index.ts:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/navigation/HomeDrawerNavigator.tsx:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/navigation/index.tsx:13:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at App.tsx:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
```

Warning log for required **removeListeners**
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
at node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:67:8 in constructor
at node_modules/getsocial-react-native-sdk/GetSocialEventEmitter.js:9:9 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/utils/JSONBridge.js:63:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/GetSocial.js:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/getsocial-react-native-sdk/index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/services/auth/hooks/useAuth.ts:31:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/services/auth/hooks/index.ts:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/navigation/HomeDrawerNavigator.tsx:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at src/navigation/index.tsx:13:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at App.tsx:4:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at index.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
```

**Comment by zolon4** [comment]
Any updates on this?
